### PR TITLE
Getting started Closes #1

### LINKED ISSUE #1: See all reminders
- When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page.
- Each reminder should have a class of `.spec-reminder-item`.

There is a failing test set up in `tests/acceptance/reminder-list-test.js`.

**Hot Tip**: If you name your pull request or even your commit with "Closes #1", it will automatically close this issue when it successfully merged into master.

### PR DESCRIPTION
**Pull request by kccrs**
## Purpose

When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page.
Each reminder should have a class of .spec-reminder-item.

https://github.com/turingschool-projects/1606-remember-8/issues/1

## Approach

_How does this change address the problem?_

I created a reminders route and a model that contains the attributes mentioned in the mirage factory. I also added the spec classname in the reminders.hbs list of reminders.

### Learning

_Describe the research stage._
_Links to blog posts, patterns, libraries or add-ons used to solve this problem._

I used Steve's beard beats demo lesson from this morning as well as a few glances at the Ember grocery list app I have in my lessons file.

https://github.com/turingschool-examples/beard-beats-two

### Open Questions and Pre-Merge TODOs

- [ ] Use Github checklists. When solved, check the box and explain the answer.

(I'M NOT REALLY SURE WHAT TO DO WITH THE ABOVE CHECKLIST.... Suggestions?)

### Test coverage 

_Briefly describe what tests you have written and why._

Well, this came with a pre-written test so I pretty much lucked out on that one.

### Merge Dependencies and Related Work

_Link to merge dependency issues or PRs._ 

I did install ember-cli-sass.  Not sure if that qualifies as an "issue" but you will need to install that as well at some point.  Is that what this section of the template is about? 

### Follow-up tasks

??  Will just await assignment of next issue.

### Screenshots

Not totally sure how to add a giphy but I'm testing it out! 
<iframe src="//giphy.com/embed/l41Ye5dhLPqILtT2w" width="480" height="269" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/new-girl-fox-comedy-new-girl-l41Ye5dhLPqILtT2w">via GIPHY</a></p>
#### After

remember-issue1-screenshot

### CODE REVIEW

**Comment by kccrs** [comment]
@stevekinney @martensonbj

**Comment by kccrs** [comment]
@brittanystoroz @tehviking

**Comment by tehviking** [comment]
I'd like to see a screenshot of the 5 reminders rendering, you can use command-shift-4, then spacebar, then click the browser window... instructions are here if you need them: https://support.apple.com/en-us/HT201361

**Comment by tehviking** [comment]
Otherwise this looks good to me

File: app/routes/application.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import Ember from 'ember';
```
Comment (stevekinney) [inline app/routes/application.js]: Let's go ahead and remove this file for now.

File: app/routes/reminders.js [hunk 2]
```diff
@@ -0,0 +1,8 @@
+
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+  model: function () {
+    return this.store.findAll('reminder');
```
Comment (stevekinney) [inline app/routes/reminders.js]: Use `this.get('store').findAll('reminder');`

File: app/routes/reminders.js [hunk 3]
```diff
@@ -0,0 +1,8 @@
+
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+  model: function () {
```
Comment (stevekinney) [inline app/routes/reminders.js]: Use the ES6 style syntax:

```
model () {
  // stuff…
}
```

File: app/templates/application.hbs [hunk 4]
```diff
@@ -0,0 +1,5 @@
+<div class="application template">
+  <h1>Welcome to Rem-Embers</h1>
+  <p>This is <em>application.hbs</em>.</p>
```
Comment (stevekinney) [inline app/templates/application.hbs]: This user doesn't need to see this.

File: app/templates/index.hbs [hunk 5]
```diff
@@ -0,0 +1,6 @@
+
+<div class="index template">
+  <p>This is <em>index.hbs</em>.</p>
```
Comment (stevekinney) [inline app/templates/index.hbs]: The user does not need to see this.

File: app/templates/reminders.hbs [hunk 6]
```diff
@@ -0,0 +1,13 @@
+<div class="reminders template">
+  <p>This is <em>reminders.hbs</em>.</p>
+
+
+  <ul>
+  {{#each model as |reminder|}}
+    <li class="spec-reminder-item">Reminder: {{reminder.title}}</li>
+    <!-- <li>{{#link-to 'reminders.reminder' reminder}}{{reminder.name}}{{/link-to}}</li> -->
```
Comment (stevekinney) [inline app/templates/reminders.hbs]: Commented out code should not be included in master.

File: app/templates/reminders.hbs [hunk 7]
```diff
@@ -0,0 +1,13 @@
+<div class="reminders template">
+  <p>This is <em>reminders.hbs</em>.</p>
+
+
+  <ul>
+  {{#each model as |reminder|}}
+    <li class="spec-reminder-item">Reminder: {{reminder.title}}</li>
```
Comment (stevekinney) [inline app/templates/reminders.hbs]: `<li>` doesn't feel like the right semantic tags. Let's to `<section>` and `<articles>`.

File: app/routes/reminders.js (hunk 2 above)
Comment (kccrs) [inline app/routes/reminders.js]: Ok, so I'm a little confused because I took this syntax directly from your lesson from this morning (minus the addition of "findAll": 

export default Ember.Route.extend({
  model: function () {
    return this.store.find('artist');
  }
});

So what is the difference?  I am changing it, I'm just curious for future reference.

Comment (kccrs) [inline app/routes/reminders.js]: @stevekinney 

I made this change as you suggested: 

export default Ember.Route.extend({
  model () {
    this.get('store').findAll('reminder');
  }
});

and now none of my reminders display as they did before.

Comment (kccrs) [inline app/routes/reminders.js]: I even tried model () => {} and that really broke things

File: app/templates/reminders.hbs (hunk 6 above)
Comment (kccrs) [inline app/templates/reminders.hbs]: 👍

File: app/templates/reminders.hbs (hunk 7 above)
Comment (kccrs) [inline app/templates/reminders.hbs]: 👍

File: app/templates/index.hbs (hunk 5 above)
Comment (kccrs) [inline app/templates/index.hbs]: 👍

File: app/templates/application.hbs (hunk 4 above)
Comment (kccrs) [inline app/templates/application.hbs]: 👍

File: app/routes/reminders.js (hunk 3 above)
Comment (kccrs) [inline app/routes/reminders.js]: see notes below

File: app/routes/application.js (hunk 1 above)
Comment (kccrs) [inline app/routes/application.js]: the entire application.js file?

File: app/routes/reminders.js (hunk 2 above)
Comment (stevekinney) [inline app/routes/reminders.js]: So, [here's the documentation on finding a record with Ember Data](https://guides.emberjs.com/v2.8.0/models/finding-records/) and [here is some documentation on setting a model for a route](https://guides.emberjs.com/v2.8.0/routing/specifying-a-routes-model/).

What do you think we should do?

Comment (kccrs) [inline app/routes/reminders.js]: Ah!  I forgot the word "return" in the model.  FIxed it -- now reads return this.get(.....).  I think I've made all the changes.  Let me know if this is approved.  Thank you

File: app/routes/application.js (hunk 1 above)
Comment (kccrs) [inline app/routes/application.js]: Ok it's gone.

**Comment by kccrs** [comment]
Please approve, I've made all the requested changes.
